# Site settings
title:       hygkui 
email:       hygkui_at_gmail.com 
author:      G HH
description: "share to learn"
baseurl:     ""
url:         "https://hygkui.github.io"

#Duoshuo short Name / 多说的shortname
duoshuo: hygkui

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze: 

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: hygkui
weibo_id: hygkui
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
